### ISSUE TITLE
Cook option

### ISSUE THREAD

**Issue by sarasg89** [MohammadKouchaki/Feed-the-foodie#2]
GIVEN a list of ingredients
WHEN I choose one 
THEN I am presented with 3 different recipes 

GIVEN a list of cuisines 
WHEN I choose one
THEN I am presented with 3 different recipes

**Comment by sarasg89** [comment]
@hannazo  the pictures for the recipes don't look right, I tried changing the classes but I don't really know what I'm doing, do you mind having a look? I have already merged into develop if you just want to grab the files from there



![Image](https://user-images.githubusercontent.com/118869836/217419855-5e3db20d-c57e-4ef7-bfbf-b5f69b37a7ad.png)

**Comment by hannazo** [comment]
@sarasg89 It should work properly now. Let me know if doesn't. 

I made some minor changes and added links to pages that we already have. Also moved "new search" and "view restaurants" section inside hidden recipe section. It looked weird to me to display that message before we even searched for anything. 

I tested code. Searched for different meals, ingredients, made "new search" and added to favourites. Everything worked perfectly. Great job!

The only thing I noticed is when you go to a different page and then come back, it displays your previous search. So if you previously searched for chicken, it would say "chicken" instead of "meat and fish". Maybe clear selection after click event?
